export {};

export enum UserMultiFactorAuthenticationTypeEnum {
  MULTIFAT_2FAAPP = 'MULTIFAT_2FAAPP',
  MULTIFAT_EMAIL = 'MULTIFAT_EMAIL',
  MULTIFAT_SMS = 'MULTIFAT_SMS',
  MULTIFAT_WHATSAPP = 'MULTIFAT_WHATSAPP',
  MULTIFAT_SECURITY_QUE = 'MULTIFAT_SECURITY_QUE',
  MULTIFAT_SECONDARY_DEVICE = 'MULTIFAT_SECONDARY_DEVICE',
}
